version: '3'

services:
  app:
    container_name: "customer-totem-api"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://fiap-lanchonete-api-customer-totem-postgres-1:5432/customertotem
      SERVER_PORT: 80
      RABBIT_HOST: rabbitmq
    networks:
      - shared
    ports:
      - "80:80"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: customertotem
    networks:
      - shared
    ports:
      - "5432:5432"

  rabbitmq:
      build:
        context: .
        dockerfile: Dockerfile-rabbit
      container_name: rabbitmq
      networks:
        - shared
      ports:
        - "5672:5672"
        - "15672:15672"

networks:
  shared:

